import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.EARLYPASS_CONFIG;
const app=document.querySelector('#app');
const supabase=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
let user=null,profile=null,classroom=null,students=[],periods=[],dayRow=null,page='dashboard',modalNode=null,boardSession=null,selectedDate=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA').format(new Date());
const time=s=>String(s||'').slice(0,5);
const toast=m=>{const n=document.createElement('div');n.className='toast';n.textContent=m;document.body.append(n);setTimeout(()=>n.remove(),3200)};
function errMsg(e){return e?.message||'Something went wrong. Please try again.'}
function showError(m){const n=document.querySelector('#msg');if(n){n.className='notice error';n.textContent=m;n.hidden=false}else toast(m)}
function login(){app.innerHTML=`<main class="login-wrap"><section class="login-brand"><div class="brand">early<em>pass</em></div><div class="brand-copy"><h1>Arrive early.<br><em>Unlock something special.</em></h1><p>Small steps from each student add up to something great for the whole class.</p></div><div class="brand-foot">A positive start to every school day.</div></section><section class="login-panel"><form class="login-card" id="login"><div class="eyebrow">EARLYPASS · SECURE ACCOUNT</div><h2>Welcome back</h2><p>Sign in with the account your school provided.</p><div id="msg" class="notice" hidden></div><div class="field"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required></div><button class="primary wide" type="submit">Sign in</button><div class="login-links"><button class="link" type="button" id="forgot">Forgot password?</button><a class="link" href="./demo.html">Explore demo</a></div></form></section></main>`;
document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button[type=submit]');b.disabled=true;b.textContent='Signing in…';const {error}=await supabase.auth.signInWithPassword({email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value});b.disabled=false;b.textContent='Sign in';if(error)showError(errMsg(error));else await boot();};
document.querySelector('#forgot').onclick=async()=>{const email=document.querySelector('#email').value.trim();if(!email){showError('Enter your email above first.');return;}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)showError(errMsg(error));else{const n=document.querySelector('#msg');n.hidden=false;n.className='notice success';n.textContent='If that account exists, a password reset email is on its way.';}};
}
function shell(){const nav=profile.role==='STUDENT'?[['student','My dashboard'],['history','My attendance'],['arrivals','My early arrivals'],['board','Class progress']]:[['dashboard','Dashboard'],['students','Students'],['attendance','Attendance'],['periods','Periods'],['earlypass','EarlyPass'],['board','Classroom board'],['settings','Settings']];
app.innerHTML=`<div class="layout"><aside class="side"><div class="side-head"><div class="brand">early<em>pass</em></div><button class="close-menu secondary" id="close-menu" type="button" aria-label="Close dashboard menu">✕</button></div><div class="school"><b>${esc(classroom.class_name)}${esc(classroom.section)}</b><small>${esc(profile.role)} · ${esc(profile.display_name)}</small></div><nav class="nav">${nav.map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}">${label}</button>`).join('')}</nav><div class="side-bottom"><div class="account"><span class="avatar">${esc((profile.display_name||'?').slice(0,1).toUpperCase())}</span><span><b>${esc(profile.display_name)}</b><small>${esc(profile.role)}</small></span><button id="logout" class="logout">Sign out</button></div></div></aside><main class="main"><header class="top"><button class="mobile-menu secondary" id="menu">☰</button><span>${esc(new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}))}</span><span class="online">● Secure account</span></header><section class="content" id="content"></section></main></div><div id="modal-root"></div>`;
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{page=x.dataset.page;render()});document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();profile=null;classroom=null;login()};document.querySelector('#menu').onclick=()=>{const layout=document.querySelector('.layout'),side=document.querySelector('.side');if(matchMedia('(max-width: 940px)').matches)side.classList.toggle('show');else layout.classList.toggle('sidebar-closed')};document.querySelector('#close-menu').onclick=()=>document.querySelector('.side').classList.remove('show');
}
async function loadDay(forDate=today()){let q=await supabase.from('class_days').select('*').eq('classroom_id',classroom.id).eq('day',forDate).maybeSingle();if(q.error)throw q.error;dayRow=q.data;if(!dayRow&&profile.role!=='STUDENT'&&forDate===today()){const ins=await supabase.from('class_days').insert({classroom_id:classroom.id,day:forDate}).select().single();if(ins.error)throw ins.error;dayRow=ins.data}if(dayRow&&profile.role!=='STUDENT'){const existing=await supabase.from('earlypass_rewards').select('id').eq('class_day_id',dayRow.id).maybeSingle();if(existing.error)throw existing.error;if(!existing.data){const goal=await supabase.from('earlypass_rewards').insert({class_day_id:dayRow.id,target:classroom.earlypass_target,reward:'Mystery Puzzle'});if(goal.error)throw goal.error}}}
async function loadShared(){const [s,p]=await Promise.all([supabase.from('students').select('*').eq('classroom_id',classroom.id).eq('active',true).order('roll_number'),supabase.from('periods').select('*').eq('classroom_id',classroom.id).order('position')]);if(s.error)throw s.error;if(p.error)throw p.error;students=s.data||[];periods=p.data||[];await loadDay()}
async function boot(){const {data:{user:u}}=await supabase.auth.getUser();user=u;if(!u){login();return}const {data:p,error}=await supabase.from('profiles').select('*').eq('user_id',u.id).maybeSingle();if(error||!p){await supabase.auth.signOut();login();showError(error?errMsg(error):'This account is not provisioned by your school. Ask an administrator.');return}profile=p;
if(p.role==='STUDENT'){const {data:s,error:se}=await supabase.from('students').select('*').eq('id',p.student_id).single();if(se||!s){await supabase.auth.signOut();login();showError(se?errMsg(se):'No student profile is linked to this account.');return}const {data:c,error:ce}=await supabase.from('classrooms').select('*').eq('id',s.classroom_id).single();if(ce){login();showError(errMsg(ce));return}classroom=c;students=[s];const {data:ps}=await supabase.from('periods').select('*').eq('classroom_id',c.id).order('position');periods=ps||[];const {data:d}=await supabase.from('class_days').select('*').eq('classroom_id',c.id).eq('day',today()).maybeSingle();dayRow=d}
else if(p.role==='ADMIN'){const {data:c,error:ce}=await supabase.from('classrooms').select('*').eq('school_id',p.school_id).limit(1).maybeSingle();if(ce||!c){login();showError(ce?errMsg(ce):'No classroom is set up for this school yet.');return}classroom=c;await loadShared()}else {const {data:t,error:te}=await supabase.from('classroom_teachers').select('classroom_id, classrooms(*)').eq('user_id',u.id).limit(1).maybeSingle();if(te||!t?.classrooms){login();showError(te?errMsg(te):'No class is assigned to this teacher account yet. Ask an administrator to assign your classroom.');return}classroom=t.classrooms;await loadShared()}
shell();render()}
function title(a,b,action=''){return `<div class="page-title"><div><h1>${a}</h1><p>${b}</p></div>${action}</div>`}
function card(a,b){return `<article class="card metric"><label>${a}</label><strong>${b}</strong></article>`}
async function render(){if(!profile)return;if(page==='board'&&!boardSession){boardView();return}try{if(profile.role!=='STUDENT')await loadShared();else if(['student','history','arrivals'].includes(page)){/* RLS limits queries to the linked student. */}const c=document.querySelector('#content');if(!c)return;c.innerHTML=page==='students'?await studentsPage():page==='attendance'?await attendancePage():page==='periods'?periodsPage():page==='earlypass'?await earlyPage():page==='settings'?settingsPage():page==='history'?await studentHistory():page==='arrivals'?await studentArrivals():page==='student'?await studentHome():page==='board'?boardView():await dashboard();const dateInput=document.querySelector('#att-date');if(dateInput)dateInput.onchange=()=>{selectedDate=dateInput.value||today();render()};const f=document.querySelector('#student-filter');if(f)f.oninput=()=>{document.querySelectorAll('[data-name]').forEach(r=>r.hidden=!r.dataset.name.includes(f.value.toLowerCase()))}}catch(e){document.querySelector('#content').innerHTML=`<div class="notice error">${esc(errMsg(e))}</div>`}}
async function counts(){if(!dayRow)return{arr:[],att:[]};const [a,t]=await Promise.all([supabase.from('arrivals').select('status').eq('class_day_id',dayRow.id),supabase.from('attendance').select('status').eq('class_day_id',dayRow.id)]);if(a.error)throw a.error;if(t.error)throw t.error;return{arr:a.data||[],att:t.data||[]}}
async function dashboard(){const {arr,att}=await counts(),early=arr.filter(x=>x.status==='EARLY').length,target=classroom.earlypass_target,unlocked=early>=target;return title(`Good morning, ${esc(profile.display_name)}`,`A positive start for ${esc(classroom.class_name)}${esc(classroom.section)}.`,`<button class="primary" data-action="attendance">Take attendance</button>`)+`<div class="grid metrics">${card('Early arrivals',early+' / '+target)}${card('Students',students.length)}${card('Periods today',periods.length)}${card('Attendance marks',att.length)}</div><div class="grid twocol"><section class="card"><div class="eyebrow">TODAY'S EARLYPASS</div><h2>${unlocked?'🎉 EarlyPass unlocked!':'Small steps, big team energy.'}</h2><p class="muted">${unlocked?'The class reward is ready.':'Every early arrival adds to the team goal.'}</p><div class="progress"><i style="width:${Math.min(100,early/target*100)}%"></i></div><b>${early} / ${target}</b> students arrived early</section><section class="card reward"><div class="eyebrow">CLASS REWARD</div><h2>${unlocked?'🎉 Ready for everyone':'A little mystery awaits'}</h2><p>${unlocked?'The class reached its shared goal.':'Reach the shared goal to reveal today’s activity.'}</p><button class="secondary" data-action="board">Open classroom board</button></section></div>`}
async function studentsPage(){return title('Students','Manage the roster for your assigned class.',`<button class="primary" data-action="add-student">＋ Add student</button>`)+`<section class="card"><div class="toolbar"><input id="student-filter" class="search" placeholder="Search name, roll or student ID"><span class="muted">${students.length} students</span></div><div class="table-wrap"><table class="table"><thead><tr><th>STUDENT</th><th>ROLL</th><th>STUDENT ID</th><th>EMAIL</th><th></th></tr></thead><tbody>${students.map(s=>`<tr data-name="${esc((s.name+' '+s.roll_number+' '+s.student_code).toLowerCase())}"><td><b>${esc(s.name)}</b></td><td>${esc(s.roll_number)}</td><td>${esc(s.student_code)}</td><td>${esc(s.email||'—')}</td><td><button class="secondary" data-action="edit-student" data-id="${s.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No students yet. Add your first class member.</td></tr>'}</tbody></table></div></section>`}
async function attendancePage(){selectedDate=selectedDate||today();await loadDay(selectedDate);if(!dayRow)return title('Attendance','No class session exists for this date.')+'<div class="empty">There are no attendance records for this date.</div>';const {data:rows,error}=await supabase.from('attendance').select('student_id,period_id,status').eq('class_day_id',dayRow.id);if(error)throw error;let index=new Map((rows||[]).map(r=>[r.student_id+':'+r.period_id,r.status]));return title('Attendance','Mark attendance for every period. Only teachers can make changes.',`<input id="att-date" class="search" type="date" value="${esc(selectedDate)}">`)+`<section class="card"><div class="toolbar"><b>Daily attendance · ${esc(selectedDate)}</b><span class="muted">Tap a status to cycle</span></div><div class="table-wrap"><table class="table"><thead><tr><th>ROLL</th><th>STUDENT</th>${periods.map(p=>`<th>${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${students.map(s=>`<tr><td>${esc(s.roll_number)}</td><td><b>${esc(s.name)}</b></td>${periods.map(p=>{let st=index.get(s.id+':'+p.id)||'';return `<td><button class="status ${st}" data-action="cycle" data-id="${s.id}|${p.id}">${st==='PRESENT'?'✓':st==='LATE'?'L':st==='ABSENT'?'A':st==='EXCUSED'?'E':'—'}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">Present · Late · Absent · Excused</p></section>`}
function periodsPage(){return title('Periods','Every period can have its own attendance.',`<button class="primary" data-action="add-period">＋ Add period</button>`)+`<section class="card">${periods.map((p,i)=>`<div class="period-row"><b>${String(i+1).padStart(2,'0')}</b><div><b>${esc(p.subject||p.name)}</b><small class="muted"> · ${esc(p.name)}</small></div><span>${esc(time(p.starts_at))} – ${esc(time(p.ends_at))}</span><span>${esc(p.room||classroom.room)}</span><div class="inline"><button class="secondary" data-action="edit-period" data-id="${p.id}">Edit</button><button class="danger" data-action="delete-period" data-id="${p.id}">Delete</button></div></div>`).join('')||'<div class="empty">Add periods to begin.</div>'}</section>`}
async function earlyPage(){const {arr}=await counts(),early=arr.filter(x=>x.status==='EARLY').length,target=classroom.earlypass_target;const {data:r}=dayRow?await supabase.from('earlypass_rewards').select('*').eq('class_day_id',dayRow.id).maybeSingle():{data:null};return title('EarlyPass','One collective goal. A celebration for everyone.',`<button class="secondary" data-action="edit-goal">⚙ Configure goal</button>`)+`<div class="grid twocol"><section class="card"><div class="eyebrow">TODAY'S EARLYPASS</div><h2>${early>=target?'🎉 EARLYPASS UNLOCKED!':'Arrive early. Unlock something special.'}</h2><div class="progress"><i style="width:${Math.min(100,early/target*100)}%"></i></div><div class="board-count">${early} <span>/ ${target}</span></div><p class="muted">${early>=target?'The whole class earned today’s activity.':Math.max(0,target-early)+' more early arrivals needed.'}</p></section><section class="card reward"><div class="eyebrow">CLASS REWARD</div><h2>${esc(r?.reward||'Mystery Puzzle')}</h2><p>${early>=target?'Unlocked for the whole class.':'The activity stays secret until the goal is reached.'}</p></section></div>`}
function settingsPage(){return title('Settings','Class and classroom access settings.')+`<div class="grid twocol"><section class="card"><div class="eyebrow">CLASS DETAILS</div><h2>${esc(classroom.class_name)}${esc(classroom.section)} · ${esc(classroom.room)}</h2><p class="muted">Starts at ${esc(time(classroom.class_start))}</p><button class="secondary" data-action="edit-class">Edit class settings</button></section><section class="card"><div class="eyebrow">CLASSROOM BOARD</div><h2>Protected shared display</h2><p class="muted">Configure a classroom access code of at least 12 characters. Students share this board; no personal attendance is shown there.</p><button class="secondary" data-action="board">Open classroom board</button></section></div><section class="card" style="margin-top:18px"><div class="eyebrow">ACCOUNT & PERMISSIONS</div><p class="muted">Signed in as ${esc(profile.role)}. Role permissions come from your school-managed profile. Student accounts cannot change attendance or class settings.</p></section>`}
async function studentRows(){const {data:a,error}=await supabase.from('attendance').select('class_day_id,period_id,status,marked_at').eq('student_id',profile.student_id).order('marked_at',{ascending:false});if(error)throw error;return a||[]}
async function studentHome(){const s=students[0],a=await studentRows(),percent=a.length?Math.round(a.filter(x=>x.status==='PRESENT'||x.status==='LATE').length/a.length*100):0;return title('My dashboard',`Welcome, ${esc(s.name)}.`)+`<div class="grid metrics">${card('Student ID',esc(s.student_code))}${card('Roll number',esc(s.roll_number))}${card('Attendance',percent+'%')}${card('Class',esc(classroom.class_name)+esc(classroom.section))}</div><section class="card"><h2>Your progress</h2><p class="muted">Every period counts. Keep showing up and taking part.</p><button class="secondary" data-action="history">View my attendance</button></section>`}
async function studentHistory(){const rows=await studentRows();const days=rows.map(x=>x.class_day_id);let dates={};if(days.length){const {data:d}=await supabase.from('class_days').select('id,day').in('id',[...new Set(days)]);for(const x of d||[])dates[x.id]=x.day}return title('My attendance','Your own period-by-period history.')+`<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>DATE</th><th>PERIOD</th><th>STATUS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(dates[r.class_day_id]||'—')}</td><td>${esc(periods.find(p=>p.id===r.period_id)?.name||'Period')}</td><td><span class="badge">${esc(r.status)}</span></td></tr>`).join('')||'<tr><td colspan="3" class="empty">No attendance history yet.</td></tr>'}</tbody></table></div></section>`}
async function studentArrivals(){const {data:a,error}=await supabase.from('arrivals').select('class_day_id,status,arrived_at').eq('student_id',profile.student_id).order('arrived_at',{ascending:false});if(error)throw error;const ids=[...new Set((a||[]).map(x=>x.class_day_id))],map={};if(ids.length){const {data:d}=await supabase.from('class_days').select('id,day').in('id',ids);for(const x of d||[])map[x.id]=x.day}return title('My early arrivals','Your personal history stays private.')+`<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>DATE</th><th>ARRIVAL</th><th>STATUS</th></tr></thead><tbody>${(a||[]).map(x=>`<tr><td>${esc(map[x.class_day_id]||'—')}</td><td>${esc(new Date(x.arrived_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="3" class="empty">No arrival history yet.</td></tr>'}</tbody></table></div></section>`}
function boardView(){const c=document.querySelector('#content');if(!c)return;c.innerHTML=title('Classroom board','Shared class progress. Student names and personal records are not shown.')+`<div class="board-wrap"><section class="board"><div class="brand">early<em>pass</em> <span class="badge">CLASS ${esc(classroom.class_name)}${esc(classroom.section)}</span></div><div class="eyebrow" style="color:#a8ecc9;margin-top:50px">GOOD MORNING, CLASS ${esc(classroom.class_name)}${esc(classroom.section)}!</div><h1>Arrive early.<br><em>Unlock something special.</em></h1><p class="board-count" id="board-progress">— <span>/ —</span></p><div class="progress"><i id="board-fill" style="width:0%"></i></div><p class="reward-name" id="board-status">Class progress is loading…</p><p class="small">${esc(classroom.room||'Classroom')} · Shared classroom display</p>${profile.role==='STUDENT'?'':'<button class="board-cta" data-action="board-checkin">Check in for this period</button>'}</section></div>`;refreshBoard().catch(e=>toast(errMsg(e)))}
async function refreshBoard(){if(!dayRow){document.querySelector('#board-status').textContent='Today’s class session is not available.';return}const [a,{data:g}]=await Promise.all([supabase.from('arrivals').select('status').eq('class_day_id',dayRow.id),supabase.from('earlypass_rewards').select('target,reward').eq('class_day_id',dayRow.id).maybeSingle()]);if(a.error)throw a.error;const early=(a.data||[]).filter(x=>x.status==='EARLY').length,target=g?.target||classroom.earlypass_target,done=early>=target;$('#board-progress').innerHTML=early+` <span>/ ${target}</span>`;$('#board-fill').style.width=Math.min(100,early/target*100)+'%';$('#board-status').textContent=done?'🎉 EARLYPASS UNLOCKED! · '+(g?.reward||'Class activity'):(target-early)+' more early arrivals needed';setTimeout(()=>{if(page==='board')refreshBoard().catch(()=>{})},30000)}
function $(s){return document.querySelector(s)}
function modal(title,body){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><header><h2>${title}</h2><button class="secondary" data-close>Close</button></header><div class="modal-body">${body}</div></section></div>`;root.querySelector('[data-close]').onclick=()=>root.innerHTML='';return root.querySelector('.modal')}
function formHtml(fields){return `<form class="form-row">${fields.map(([label,name,type='text',value='',required=true])=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></div>`).join('')}<button class="primary wide" style="grid-column:1/-1">Save</button></form>`}
async function action(a,id){if(a==='attendance'){page='attendance';render();return}if(a==='board'){page='board';boardSession=null;render();return}if(a==='history'){page='history';render();return}
if(a==='add-student'||a==='edit-student'){const s=students.find(x=>x.id===id)||{},m=modal(a==='add-student'?'Add student':'Edit student',formHtml([['Student name','name','text',s.name||''],['Roll number','roll_number','text',s.roll_number||''],['Student ID','student_code','text',s.student_code||'',false],['Email (optional)','email','email',s.email||'',false]]));m.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const payload={name:v.name.trim(),roll_number:v.roll_number.trim(),student_code:v.student_code.trim()||'EP-'+classroom.class_name+classroom.section+'-'+crypto.randomUUID().slice(0,8).toUpperCase(),email:v.email||null,school_id:classroom.school_id,classroom_id:classroom.id};const q=s.id?await supabase.from('students').update(payload).eq('id',s.id):await supabase.from('students').insert(payload);if(q.error){showError(errMsg(q.error));return}$('#modal-root').innerHTML='';toast('Student saved.');render()};return}
if(a==='add-period'||a==='edit-period'){const p=periods.find(x=>x.id===id)||{},m=modal(a==='add-period'?'Add period':'Edit period',formHtml([['Period name','name','text',p.name||'Period '+(periods.length+1)],['Subject','subject','text',p.subject||''],['Start time','starts_at','time',time(p.starts_at)||'08:30'],['End time','ends_at','time',time(p.ends_at)||'09:15'],['Teacher','teacher_name','text',p.teacher_name||profile.display_name],['Room','room','text',p.room||classroom.room]]));m.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const payload={...v,position:p.position||periods.length+1,classroom_id:classroom.id};const q=p.id?await supabase.from('periods').update(payload).eq('id',p.id):await supabase.from('periods').insert(payload);if(q.error){showError(errMsg(q.error));return}$('#modal-root').innerHTML='';render()};return}
if(a==='delete-period'){if(!confirm('Delete this period? Existing historical attendance may prevent deletion.'))return;const {error}=await supabase.from('periods').delete().eq('id',id);if(error)showError(errMsg(error));else{toast('Period deleted.');render()}return}
if(a==='cycle'){if(profile.role==='STUDENT')return;let [student_id,period_id]=id.split('|'),statuses=['PRESENT','LATE','ABSENT','EXCUSED'],{data:old}=await supabase.from('attendance').select('status').eq('class_day_id',dayRow.id).eq('student_id',student_id).eq('period_id',period_id).maybeSingle(),next=statuses[(statuses.indexOf(old?.status)+1)%statuses.length];const {error}=await supabase.from('attendance').upsert({class_day_id:dayRow.id,student_id,period_id,status:next,marked_by:user.id},{onConflict:'class_day_id,student_id,period_id'});if(error)showError(errMsg(error));else render();return}
if(a==='edit-goal'){const m=modal('Configure EarlyPass goal',formHtml([['EarlyPass target','target','number',classroom.earlypass_target],['Today’s reward','reward','text','Mystery Puzzle']]));m.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),target=Math.max(1,Number(v.target));const {error}=await supabase.from('classrooms').update({earlypass_target:target}).eq('id',classroom.id);if(error){showError(errMsg(error));return}classroom.earlypass_target=target;if(dayRow){const q=await supabase.from('earlypass_rewards').upsert({class_day_id:dayRow.id,target,reward:v.reward},{onConflict:'class_day_id'});if(q.error){showError(errMsg(q.error));return}}$('#modal-root').innerHTML='';toast('EarlyPass goal saved.');render()};return}
if(a==='edit-class'){const m=modal('Edit class settings',formHtml([['Class start','class_start','time',time(classroom.class_start)],['Early arrival window (minutes)','early_window_minutes','number',classroom.early_window_minutes],['Room','room','text',classroom.room||'']]));m.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const {error}=await supabase.from('classrooms').update({...v,early_window_minutes:Number(v.early_window_minutes)}).eq('id',classroom.id);if(error){showError(errMsg(error));return}Object.assign(classroom,v);$('#modal-root').innerHTML='';render()};return}

if(a==='board-checkin'){const {data:ps}=await supabase.from('periods').select('*').eq('classroom_id',classroom.id).order('position');const m=modal('Check in for this period',`<p class="muted">Choose your own name. Check-ins are recorded securely; personal status is not displayed on the shared board.</p><div class="field"><label>Your name</label><select id="board-student">${students.map(s=>`<option value="${s.id}">${esc(s.roll_number)} · ${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Period</label><select id="board-period">${(ps||[]).map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(time(p.starts_at))}</option>`).join('')}</select></div><button class="primary wide" id="send-checkin">Check in</button>`);m.querySelector('#send-checkin').onclick=async()=>{const student_id=m.querySelector('#board-student').value,period_id=m.querySelector('#board-period').value;if(!student_id||!period_id){showError('Select a student and period.');return}if(!dayRow){showError('Today’s class session is unavailable.');return}const current=new Date(),hh=String(current.getHours()).padStart(2,'0'),mm=String(current.getMinutes()).padStart(2,'0'),nowTime=hh+':'+mm,cutoff=String(classroom.class_start).slice(0,5),earlyBy=Number(classroom.early_window_minutes||15),mins=x=>{const [h,m]=String(x).split(':').map(Number);return h*60+m},arrivalStatus=mins(nowTime)<mins(cutoff)-earlyBy?'EARLY':mins(nowTime)<=mins(cutoff)?'ON_TIME':'LATE',period=periods.find(p=>p.id===period_id),periodStatus=mins(nowTime)>mins(period.starts_at)?'LATE':'PRESENT';const arrival=await supabase.from('arrivals').upsert({class_day_id:dayRow.id,student_id,arrived_at:current.toISOString(),status:arrivalStatus,recorded_by:user.id},{onConflict:'class_day_id,student_id',ignoreDuplicates:true});if(arrival.error){showError(errMsg(arrival.error));return}const mark=await supabase.from('attendance').upsert({class_day_id:dayRow.id,student_id,period_id,status:periodStatus,marked_by:user.id},{onConflict:'class_day_id,student_id,period_id'});if(mark.error){showError(errMsg(mark.error));return}const {arr}=await counts();if(arr.filter(x=>x.status==='EARLY').length>=Number(classroom.earlypass_target)){await supabase.from('earlypass_rewards').update({unlocked_at:new Date().toISOString()}).eq('class_day_id',dayRow.id)}$('#modal-root').innerHTML='';toast('Check-in saved. Thank you for participating!');await render()};return}
}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)action(a.dataset.action,a.dataset.id).catch(err=>showError(errMsg(err)))});
supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){profile=null;login()}});
if(cfg?.supabaseUrl&&cfg?.supabasePublishableKey)boot().catch(e=>{login();showError(errMsg(e))});else login();
